project:
  type: website
  output-dir: docs
  preview: 
    port: 4007
    browser: true

website:
  title: "Experimental"
  site-url: "" # a.k.a baseurl
  # favicon: "resources/img/favicon.png"
  navbar:
    left:
      - href: index.qmd
        text: Home

    right:
      - icon: github
        href: https://www.github.com/koushikkhan/
      

format:
  html:
    mainfont: system-ui
    html-math-method: katex
    mermaid: 
      theme: default
    theme:
      light: flatly
      dark: darkly
    toc: true
    code-block-bg: true
    code-block-border-left: true
    highlight-style: atom-one
    code-line-numbers: true